version: '3.8'

services:
  frontend:
    stdin_open: true
    container_name: melochord-frontend
    build:
      context: ./
      dockerfile: ./Dockerfile        
    env_file: ./.env         
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - host.docker.internal:172.17.0.1
      - localhost:127.0.0.1
    networks:
      - frontend 
    cpu_period: 10000
    cpu_quota: 2500  

networks:
  frontend:
    name: frontend
    external: true