version: '3.8'

services:
  frontend:
    container_name: melochord-frontend
    env_file: ./.env
    build:
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'    
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "host.docker.internal:172.17.0.1"  
    networks:
      - frontend 
      

networks:
  frontend: